analyzer:
  plugins:
    - custom_lint

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

custom_lint:
  # Enable all Flutter Compositions lint rules
  enable_all_lint_rules: true

  # Or selectively enable/disable rules
  rules:
    # Ensures reactive props usage (Warning)
    - flutter_compositions_ensure_reactive_props: true

    # Prevents async setup functions (Error)
    - flutter_compositions_no_async_setup: true

    # Manages controller lifecycle (Warning)
    - flutter_compositions_controller_lifecycle: true

    # Warns about shallow reactivity (Warning)
    - flutter_compositions_shallow_reactivity: true

    # Prevents conditional composition API calls (Error)
    - flutter_compositions_no_conditional_composition: true
